package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.NeeqCompanyChoiceLayerOnline;
import com.kf.data.mybatis.entity.NeeqCompanyChoiceLayerOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyChoiceLayerOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int countByExample(NeeqCompanyChoiceLayerOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int deleteByExample(NeeqCompanyChoiceLayerOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int insert(NeeqCompanyChoiceLayerOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int insertSelective(NeeqCompanyChoiceLayerOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    List<NeeqCompanyChoiceLayerOnline> selectByExample(NeeqCompanyChoiceLayerOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    NeeqCompanyChoiceLayerOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyChoiceLayerOnline record, @Param("example") NeeqCompanyChoiceLayerOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int updateByExample(@Param("record") NeeqCompanyChoiceLayerOnline record, @Param("example") NeeqCompanyChoiceLayerOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int updateByPrimaryKeySelective(NeeqCompanyChoiceLayerOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_choice_layer
     *
     * @mbggenerated Tue Dec 19 10:51:34 CST 2017
     */
    int updateByPrimaryKey(NeeqCompanyChoiceLayerOnline record);
}