package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.NeeqCompanyNotice;
import com.kf.data.mybatis.entity.NeeqCompanyNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int countByExample(NeeqCompanyNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int deleteByExample(NeeqCompanyNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int insert(NeeqCompanyNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int insertSelective(NeeqCompanyNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    List<NeeqCompanyNotice> selectByExample(NeeqCompanyNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    NeeqCompanyNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyNotice record, @Param("example") NeeqCompanyNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int updateByExample(@Param("record") NeeqCompanyNotice record, @Param("example") NeeqCompanyNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int updateByPrimaryKeySelective(NeeqCompanyNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Tue Sep 19 16:01:49 CST 2017
     */
    int updateByPrimaryKey(NeeqCompanyNotice record);
}