package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.NeeqInformationLawsCrawler;
import com.kf.data.mybatis.entity.NeeqInformationLawsCrawlerExample;
import com.kf.data.mybatis.entity.NeeqInformationLawsCrawlerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqInformationLawsCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int countByExample(NeeqInformationLawsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int deleteByExample(NeeqInformationLawsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int insert(NeeqInformationLawsCrawlerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int insertSelective(NeeqInformationLawsCrawlerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    List<NeeqInformationLawsCrawlerWithBLOBs> selectByExampleWithBLOBs(NeeqInformationLawsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    List<NeeqInformationLawsCrawler> selectByExample(NeeqInformationLawsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    NeeqInformationLawsCrawlerWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") NeeqInformationLawsCrawlerWithBLOBs record, @Param("example") NeeqInformationLawsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqInformationLawsCrawlerWithBLOBs record, @Param("example") NeeqInformationLawsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int updateByExample(@Param("record") NeeqInformationLawsCrawler record, @Param("example") NeeqInformationLawsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int updateByPrimaryKeySelective(NeeqInformationLawsCrawlerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(NeeqInformationLawsCrawlerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_information_laws
     *
     * @mbggenerated Fri Nov 24 16:44:33 CST 2017
     */
    int updateByPrimaryKey(NeeqInformationLawsCrawler record);
}