package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.PdfCodeChapter;
import com.kf.data.mybatis.entity.PdfCodeChapterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdfCodeChapterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int countByExample(PdfCodeChapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int deleteByExample(PdfCodeChapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int insert(PdfCodeChapter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int insertSelective(PdfCodeChapter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	List<PdfCodeChapter> selectByExample(PdfCodeChapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	PdfCodeChapter selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PdfCodeChapter record,
			@Param("example") PdfCodeChapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int updateByExample(@Param("record") PdfCodeChapter record, @Param("example") PdfCodeChapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int updateByPrimaryKeySelective(PdfCodeChapter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	int updateByPrimaryKey(PdfCodeChapter record);
}