package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.PdfReportTableModel;
import com.kf.data.mybatis.entity.PdfReportTableModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdfReportTableModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int countByExample(PdfReportTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int deleteByExample(PdfReportTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int insert(PdfReportTableModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int insertSelective(PdfReportTableModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	List<PdfReportTableModel> selectByExample(PdfReportTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	PdfReportTableModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PdfReportTableModel record,
			@Param("example") PdfReportTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int updateByExample(@Param("record") PdfReportTableModel record,
			@Param("example") PdfReportTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int updateByPrimaryKeySelective(PdfReportTableModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_table_model
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int updateByPrimaryKey(PdfReportTableModel record);
}