package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.PdfReportModelNotice;
import com.kf.data.mybatis.entity.PdfReportModelNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdfReportModelNoticeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int countByExample(PdfReportModelNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int deleteByExample(PdfReportModelNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int insert(PdfReportModelNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int insertSelective(PdfReportModelNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	List<PdfReportModelNotice> selectByExample(PdfReportModelNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	PdfReportModelNotice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PdfReportModelNotice record,
			@Param("example") PdfReportModelNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int updateByExample(@Param("record") PdfReportModelNotice record,
			@Param("example") PdfReportModelNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int updateByPrimaryKeySelective(PdfReportModelNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_report_model_notice
	 * @mbggenerated  Fri Sep 22 19:07:34 CST 2017
	 */
	int updateByPrimaryKey(PdfReportModelNotice record);
}