package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.PdPedailyEventCrawler;
import com.kf.data.mybatis.entity.PdPedailyEventCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdPedailyEventCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int countByExample(PdPedailyEventCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int deleteByExample(PdPedailyEventCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int insert(PdPedailyEventCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int insertSelective(PdPedailyEventCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    List<PdPedailyEventCrawler> selectByExample(PdPedailyEventCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    PdPedailyEventCrawler selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") PdPedailyEventCrawler record, @Param("example") PdPedailyEventCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int updateByExample(@Param("record") PdPedailyEventCrawler record, @Param("example") PdPedailyEventCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int updateByPrimaryKeySelective(PdPedailyEventCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_pedaily_event
     *
     * @mbggenerated Fri Nov 24 10:37:49 CST 2017
     */
    int updateByPrimaryKey(PdPedailyEventCrawler record);
}