package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyRecruitmentCrawler;
import com.kf.data.mybatis.entity.TycCompanyRecruitmentCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyRecruitmentCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int countByExample(TycCompanyRecruitmentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByExample(TycCompanyRecruitmentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insert(TycCompanyRecruitmentCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insertSelective(TycCompanyRecruitmentCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	List<TycCompanyRecruitmentCrawler> selectByExampleWithBLOBs(TycCompanyRecruitmentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	List<TycCompanyRecruitmentCrawler> selectByExample(TycCompanyRecruitmentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	TycCompanyRecruitmentCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyRecruitmentCrawler record,
			@Param("example") TycCompanyRecruitmentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") TycCompanyRecruitmentCrawler record,
			@Param("example") TycCompanyRecruitmentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyRecruitmentCrawler record,
			@Param("example") TycCompanyRecruitmentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyRecruitmentCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(TycCompanyRecruitmentCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_recruitment
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyRecruitmentCrawler record);
}