package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyAdmPenaltyCrawler;
import com.kf.data.mybatis.entity.TycCompanyAdmPenaltyCrawlerExample;
import com.kf.data.mybatis.entity.TycCompanyAdmPenaltyCrawlerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyAdmPenaltyCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int countByExample(TycCompanyAdmPenaltyCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int deleteByExample(TycCompanyAdmPenaltyCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int deleteByPrimaryKey(TycCompanyAdmPenaltyCrawlerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int insert(TycCompanyAdmPenaltyCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int insertSelective(TycCompanyAdmPenaltyCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    List<TycCompanyAdmPenaltyCrawler> selectByExample(TycCompanyAdmPenaltyCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    TycCompanyAdmPenaltyCrawler selectByPrimaryKey(TycCompanyAdmPenaltyCrawlerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyAdmPenaltyCrawler record, @Param("example") TycCompanyAdmPenaltyCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyAdmPenaltyCrawler record, @Param("example") TycCompanyAdmPenaltyCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyAdmPenaltyCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_adm_penalty
     *
     * @mbggenerated Tue Oct 31 14:52:57 CST 2017
     */
    int updateByPrimaryKey(TycCompanyAdmPenaltyCrawler record);
}