package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyEquityPledgedCrawler;
import com.kf.data.mybatis.entity.TycCompanyEquityPledgedCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyEquityPledgedCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int countByExample(TycCompanyEquityPledgedCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByExample(TycCompanyEquityPledgedCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insert(TycCompanyEquityPledgedCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insertSelective(TycCompanyEquityPledgedCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	List<TycCompanyEquityPledgedCrawler> selectByExample(TycCompanyEquityPledgedCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	TycCompanyEquityPledgedCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyEquityPledgedCrawler record,
			@Param("example") TycCompanyEquityPledgedCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyEquityPledgedCrawler record,
			@Param("example") TycCompanyEquityPledgedCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyEquityPledgedCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_equity_pledged
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyEquityPledgedCrawler record);
}