package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanySfpmCrawler;
import com.kf.data.mybatis.entity.TycCompanySfpmCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanySfpmCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int countByExample(TycCompanySfpmCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int deleteByExample(TycCompanySfpmCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int insert(TycCompanySfpmCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int insertSelective(TycCompanySfpmCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    List<TycCompanySfpmCrawler> selectByExample(TycCompanySfpmCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    TycCompanySfpmCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanySfpmCrawler record, @Param("example") TycCompanySfpmCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int updateByExample(@Param("record") TycCompanySfpmCrawler record, @Param("example") TycCompanySfpmCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanySfpmCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_sfpm
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int updateByPrimaryKey(TycCompanySfpmCrawler record);
}