package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyCopyrightCrawler;
import com.kf.data.mybatis.entity.TycCompanyCopyrightCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyCopyrightCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int countByExample(TycCompanyCopyrightCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByExample(TycCompanyCopyrightCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insert(TycCompanyCopyrightCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insertSelective(TycCompanyCopyrightCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	List<TycCompanyCopyrightCrawler> selectByExample(TycCompanyCopyrightCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	TycCompanyCopyrightCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyCopyrightCrawler record,
			@Param("example") TycCompanyCopyrightCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyCopyrightCrawler record,
			@Param("example") TycCompanyCopyrightCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyCopyrightCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_copyright
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyCopyrightCrawler record);
}