package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyCompetitorsCrawler;
import com.kf.data.mybatis.entity.TycCompanyCompetitorsCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyCompetitorsCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int countByExample(TycCompanyCompetitorsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int deleteByExample(TycCompanyCompetitorsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int insert(TycCompanyCompetitorsCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int insertSelective(TycCompanyCompetitorsCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    List<TycCompanyCompetitorsCrawler> selectByExample(TycCompanyCompetitorsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    TycCompanyCompetitorsCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyCompetitorsCrawler record, @Param("example") TycCompanyCompetitorsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyCompetitorsCrawler record, @Param("example") TycCompanyCompetitorsCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyCompetitorsCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_competitors
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    int updateByPrimaryKey(TycCompanyCompetitorsCrawler record);
}