package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyShixinCrawler;
import com.kf.data.mybatis.entity.TycCompanyShixinCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyShixinCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int countByExample(TycCompanyShixinCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int deleteByExample(TycCompanyShixinCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int insert(TycCompanyShixinCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int insertSelective(TycCompanyShixinCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    List<TycCompanyShixinCrawler> selectByExample(TycCompanyShixinCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    TycCompanyShixinCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyShixinCrawler record, @Param("example") TycCompanyShixinCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyShixinCrawler record, @Param("example") TycCompanyShixinCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyShixinCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_shixin
     *
     * @mbggenerated Wed Nov 01 13:40:58 CST 2017
     */
    int updateByPrimaryKey(TycCompanyShixinCrawler record);
}