package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyTrademarkCrawler;
import com.kf.data.mybatis.entity.TycCompanyTrademarkCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyTrademarkCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int countByExample(TycCompanyTrademarkCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int deleteByExample(TycCompanyTrademarkCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int insert(TycCompanyTrademarkCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int insertSelective(TycCompanyTrademarkCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	List<TycCompanyTrademarkCrawler> selectByExampleWithBLOBs(TycCompanyTrademarkCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	List<TycCompanyTrademarkCrawler> selectByExample(TycCompanyTrademarkCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	TycCompanyTrademarkCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyTrademarkCrawler record,
			@Param("example") TycCompanyTrademarkCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") TycCompanyTrademarkCrawler record,
			@Param("example") TycCompanyTrademarkCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyTrademarkCrawler record,
			@Param("example") TycCompanyTrademarkCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyTrademarkCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(TycCompanyTrademarkCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_trademark
	 * @mbggenerated  Tue Nov 07 18:34:58 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyTrademarkCrawler record);
}