package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyProductCrawler;
import com.kf.data.mybatis.entity.TycCompanyProductCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyProductCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int countByExample(TycCompanyProductCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int deleteByExample(TycCompanyProductCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int insert(TycCompanyProductCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int insertSelective(TycCompanyProductCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    List<TycCompanyProductCrawler> selectByExampleWithBLOBs(TycCompanyProductCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    List<TycCompanyProductCrawler> selectByExample(TycCompanyProductCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    TycCompanyProductCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyProductCrawler record, @Param("example") TycCompanyProductCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TycCompanyProductCrawler record, @Param("example") TycCompanyProductCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyProductCrawler record, @Param("example") TycCompanyProductCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyProductCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TycCompanyProductCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_product
     *
     * @mbggenerated Tue Oct 31 18:01:02 CST 2017
     */
    int updateByPrimaryKey(TycCompanyProductCrawler record);
}