package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyZhixingCrawler;
import com.kf.data.mybatis.entity.TycCompanyZhixingCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyZhixingCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int countByExample(TycCompanyZhixingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int deleteByExample(TycCompanyZhixingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int insert(TycCompanyZhixingCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int insertSelective(TycCompanyZhixingCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    List<TycCompanyZhixingCrawler> selectByExample(TycCompanyZhixingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    TycCompanyZhixingCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyZhixingCrawler record, @Param("example") TycCompanyZhixingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyZhixingCrawler record, @Param("example") TycCompanyZhixingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyZhixingCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_zhixing
     *
     * @mbggenerated Wed Nov 01 14:04:44 CST 2017
     */
    int updateByPrimaryKey(TycCompanyZhixingCrawler record);
}