package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyCommonstockChangeCrawler;
import com.kf.data.mybatis.entity.TycCompanyCommonstockChangeCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyCommonstockChangeCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int countByExample(TycCompanyCommonstockChangeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int deleteByExample(TycCompanyCommonstockChangeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int insert(TycCompanyCommonstockChangeCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int insertSelective(TycCompanyCommonstockChangeCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    List<TycCompanyCommonstockChangeCrawler> selectByExample(TycCompanyCommonstockChangeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    TycCompanyCommonstockChangeCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyCommonstockChangeCrawler record, @Param("example") TycCompanyCommonstockChangeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyCommonstockChangeCrawler record, @Param("example") TycCompanyCommonstockChangeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyCommonstockChangeCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_commonstock_change
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    int updateByPrimaryKey(TycCompanyCommonstockChangeCrawler record);
}