package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyCaseNoticeCrawler;
import com.kf.data.mybatis.entity.TycCompanyCaseNoticeCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyCaseNoticeCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int countByExample(TycCompanyCaseNoticeCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int deleteByExample(TycCompanyCaseNoticeCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int insert(TycCompanyCaseNoticeCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int insertSelective(TycCompanyCaseNoticeCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	List<TycCompanyCaseNoticeCrawler> selectByExampleWithBLOBs(TycCompanyCaseNoticeCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	List<TycCompanyCaseNoticeCrawler> selectByExample(TycCompanyCaseNoticeCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	TycCompanyCaseNoticeCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyCaseNoticeCrawler record,
			@Param("example") TycCompanyCaseNoticeCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") TycCompanyCaseNoticeCrawler record,
			@Param("example") TycCompanyCaseNoticeCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyCaseNoticeCrawler record,
			@Param("example") TycCompanyCaseNoticeCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyCaseNoticeCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(TycCompanyCaseNoticeCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_case_notice
	 * @mbggenerated  Wed Nov 01 11:50:06 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyCaseNoticeCrawler record);
}