package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyFinancingCrawler;
import com.kf.data.mybatis.entity.TycCompanyFinancingCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyFinancingCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int countByExample(TycCompanyFinancingCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int deleteByExample(TycCompanyFinancingCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int insert(TycCompanyFinancingCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int insertSelective(TycCompanyFinancingCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	List<TycCompanyFinancingCrawler> selectByExample(TycCompanyFinancingCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	TycCompanyFinancingCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyFinancingCrawler record,
			@Param("example") TycCompanyFinancingCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyFinancingCrawler record,
			@Param("example") TycCompanyFinancingCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyFinancingCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_financing
	 * @mbggenerated  Tue Oct 31 14:26:34 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyFinancingCrawler record);
}