package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyInvestOutsideCrawler;
import com.kf.data.mybatis.entity.TycCompanyInvestOutsideCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyInvestOutsideCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int countByExample(TycCompanyInvestOutsideCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int deleteByExample(TycCompanyInvestOutsideCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int insert(TycCompanyInvestOutsideCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int insertSelective(TycCompanyInvestOutsideCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    List<TycCompanyInvestOutsideCrawler> selectByExample(TycCompanyInvestOutsideCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    TycCompanyInvestOutsideCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyInvestOutsideCrawler record, @Param("example") TycCompanyInvestOutsideCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyInvestOutsideCrawler record, @Param("example") TycCompanyInvestOutsideCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyInvestOutsideCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_invest_outside
     *
     * @mbggenerated Mon Oct 30 13:48:28 CST 2017
     */
    int updateByPrimaryKey(TycCompanyInvestOutsideCrawler record);
}