package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyChattelMortgageCrawler;
import com.kf.data.mybatis.entity.TycCompanyChattelMortgageCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyChattelMortgageCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int countByExample(TycCompanyChattelMortgageCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByExample(TycCompanyChattelMortgageCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insert(TycCompanyChattelMortgageCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insertSelective(TycCompanyChattelMortgageCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	List<TycCompanyChattelMortgageCrawler> selectByExample(TycCompanyChattelMortgageCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	TycCompanyChattelMortgageCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyChattelMortgageCrawler record,
			@Param("example") TycCompanyChattelMortgageCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyChattelMortgageCrawler record,
			@Param("example") TycCompanyChattelMortgageCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyChattelMortgageCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_chattel_mortgage
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyChattelMortgageCrawler record);
}