package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyPatentCrawler;
import com.kf.data.mybatis.entity.TycCompanyPatentCrawlerExample;
import com.kf.data.mybatis.entity.TycCompanyPatentCrawlerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyPatentCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int countByExample(TycCompanyPatentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int deleteByExample(TycCompanyPatentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int insert(TycCompanyPatentCrawlerWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int insertSelective(TycCompanyPatentCrawlerWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	List<TycCompanyPatentCrawlerWithBLOBs> selectByExampleWithBLOBs(TycCompanyPatentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	List<TycCompanyPatentCrawler> selectByExample(TycCompanyPatentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	TycCompanyPatentCrawlerWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyPatentCrawlerWithBLOBs record,
			@Param("example") TycCompanyPatentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") TycCompanyPatentCrawlerWithBLOBs record,
			@Param("example") TycCompanyPatentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyPatentCrawler record,
			@Param("example") TycCompanyPatentCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyPatentCrawlerWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(TycCompanyPatentCrawlerWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_patent
	 * @mbggenerated  Mon Oct 16 13:42:46 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyPatentCrawler record);
}