package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyTaxArrearsCrawler;
import com.kf.data.mybatis.entity.TycCompanyTaxArrearsCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyTaxArrearsCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int countByExample(TycCompanyTaxArrearsCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int deleteByExample(TycCompanyTaxArrearsCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int insert(TycCompanyTaxArrearsCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int insertSelective(TycCompanyTaxArrearsCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	List<TycCompanyTaxArrearsCrawler> selectByExample(TycCompanyTaxArrearsCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	TycCompanyTaxArrearsCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyTaxArrearsCrawler record,
			@Param("example") TycCompanyTaxArrearsCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyTaxArrearsCrawler record,
			@Param("example") TycCompanyTaxArrearsCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyTaxArrearsCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_tax_arrears
	 * @mbggenerated  Tue Oct 31 15:25:27 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyTaxArrearsCrawler record);
}