package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyCheckCrawler;
import com.kf.data.mybatis.entity.TycCompanyCheckCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyCheckCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int countByExample(TycCompanyCheckCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int deleteByExample(TycCompanyCheckCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int insert(TycCompanyCheckCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int insertSelective(TycCompanyCheckCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    List<TycCompanyCheckCrawler> selectByExample(TycCompanyCheckCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    TycCompanyCheckCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyCheckCrawler record, @Param("example") TycCompanyCheckCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyCheckCrawler record, @Param("example") TycCompanyCheckCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyCheckCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_check
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    int updateByPrimaryKey(TycCompanyCheckCrawler record);
}