package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyTaxRatingCrawler;
import com.kf.data.mybatis.entity.TycCompanyTaxRatingCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyTaxRatingCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int countByExample(TycCompanyTaxRatingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int deleteByExample(TycCompanyTaxRatingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int insert(TycCompanyTaxRatingCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int insertSelective(TycCompanyTaxRatingCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    List<TycCompanyTaxRatingCrawler> selectByExample(TycCompanyTaxRatingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    TycCompanyTaxRatingCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyTaxRatingCrawler record, @Param("example") TycCompanyTaxRatingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyTaxRatingCrawler record, @Param("example") TycCompanyTaxRatingCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyTaxRatingCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_tax_rating
     *
     * @mbggenerated Tue Oct 31 15:30:35 CST 2017
     */
    int updateByPrimaryKey(TycCompanyTaxRatingCrawler record);
}