package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyIshnteCrawler;
import com.kf.data.mybatis.entity.TycCompanyIshnteCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyIshnteCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int countByExample(TycCompanyIshnteCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int deleteByExample(TycCompanyIshnteCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int insert(TycCompanyIshnteCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int insertSelective(TycCompanyIshnteCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    List<TycCompanyIshnteCrawler> selectByExample(TycCompanyIshnteCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    TycCompanyIshnteCrawler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") TycCompanyIshnteCrawler record, @Param("example") TycCompanyIshnteCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int updateByExample(@Param("record") TycCompanyIshnteCrawler record, @Param("example") TycCompanyIshnteCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int updateByPrimaryKeySelective(TycCompanyIshnteCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_ishnte
     *
     * @mbggenerated Thu Jan 04 10:31:06 CST 2018
     */
    int updateByPrimaryKey(TycCompanyIshnteCrawler record);
}