package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyWechatCrawler;
import com.kf.data.mybatis.entity.TycCompanyWechatCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyWechatCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int countByExample(TycCompanyWechatCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int deleteByExample(TycCompanyWechatCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int insert(TycCompanyWechatCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int insertSelective(TycCompanyWechatCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	List<TycCompanyWechatCrawler> selectByExample(TycCompanyWechatCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	TycCompanyWechatCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyWechatCrawler record,
			@Param("example") TycCompanyWechatCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyWechatCrawler record,
			@Param("example") TycCompanyWechatCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyWechatCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_wechat
	 * @mbggenerated  Sat Sep 30 16:07:29 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyWechatCrawler record);
}