package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyShareholdersContributiveCrawler;
import com.kf.data.mybatis.entity.TycCompanyShareholdersContributiveCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyShareholdersContributiveCrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int countByExample(TycCompanyShareholdersContributiveCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByExample(TycCompanyShareholdersContributiveCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insert(TycCompanyShareholdersContributiveCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int insertSelective(TycCompanyShareholdersContributiveCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	List<TycCompanyShareholdersContributiveCrawler> selectByExample(
			TycCompanyShareholdersContributiveCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	TycCompanyShareholdersContributiveCrawler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycCompanyShareholdersContributiveCrawler record,
			@Param("example") TycCompanyShareholdersContributiveCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByExample(@Param("record") TycCompanyShareholdersContributiveCrawler record,
			@Param("example") TycCompanyShareholdersContributiveCrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKeySelective(TycCompanyShareholdersContributiveCrawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_shareholders_contributive
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	int updateByPrimaryKey(TycCompanyShareholdersContributiveCrawler record);
}