package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycCompanyAbnormalOperationCrawler;
import com.kf.data.mybatis.entity.TycCompanyAbnormalOperationCrawlerExample;
import com.kf.data.mybatis.entity.TycCompanyAbnormalOperationCrawlerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycCompanyAbnormalOperationCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int countByExample(TycCompanyAbnormalOperationCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int deleteByExample(TycCompanyAbnormalOperationCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int insert(TycCompanyAbnormalOperationCrawlerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int insertSelective(TycCompanyAbnormalOperationCrawlerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    List<TycCompanyAbnormalOperationCrawlerWithBLOBs> selectByExampleWithBLOBs(TycCompanyAbnormalOperationCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    List<TycCompanyAbnormalOperationCrawler> selectByExample(TycCompanyAbnormalOperationCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    TycCompanyAbnormalOperationCrawlerWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") TycCompanyAbnormalOperationCrawlerWithBLOBs record, @Param("example") TycCompanyAbnormalOperationCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TycCompanyAbnormalOperationCrawlerWithBLOBs record, @Param("example") TycCompanyAbnormalOperationCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int updateByExample(@Param("record") TycCompanyAbnormalOperationCrawler record, @Param("example") TycCompanyAbnormalOperationCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int updateByPrimaryKeySelective(TycCompanyAbnormalOperationCrawlerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TycCompanyAbnormalOperationCrawlerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_abnormal_operation
     *
     * @mbggenerated Tue Oct 31 14:36:18 CST 2017
     */
    int updateByPrimaryKey(TycCompanyAbnormalOperationCrawler record);
}