package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.TycHumans;
import com.kf.data.mybatis.entity.TycHumansExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TycHumansMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int countByExample(TycHumansExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int deleteByExample(TycHumansExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int insert(TycHumans record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int insertSelective(TycHumans record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	List<TycHumans> selectByExample(TycHumansExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	TycHumans selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TycHumans record, @Param("example") TycHumansExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int updateByExample(@Param("record") TycHumans record, @Param("example") TycHumansExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int updateByPrimaryKeySelective(TycHumans record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_humans
	 * @mbggenerated  Tue Sep 26 14:22:49 CST 2017
	 */
	int updateByPrimaryKey(TycHumans record);
}