package com.kf.data.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class PdfCodeChapterExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public PdfCodeChapterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNoticeIdIsNull() {
			addCriterion("notice_id is null");
			return (Criteria) this;
		}

		public Criteria andNoticeIdIsNotNull() {
			addCriterion("notice_id is not null");
			return (Criteria) this;
		}

		public Criteria andNoticeIdEqualTo(Integer value) {
			addCriterion("notice_id =", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdNotEqualTo(Integer value) {
			addCriterion("notice_id <>", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdGreaterThan(Integer value) {
			addCriterion("notice_id >", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("notice_id >=", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdLessThan(Integer value) {
			addCriterion("notice_id <", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdLessThanOrEqualTo(Integer value) {
			addCriterion("notice_id <=", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdIn(List<Integer> values) {
			addCriterion("notice_id in", values, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdNotIn(List<Integer> values) {
			addCriterion("notice_id not in", values, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdBetween(Integer value1, Integer value2) {
			addCriterion("notice_id between", value1, value2, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("notice_id not between", value1, value2, "noticeId");
			return (Criteria) this;
		}

		public Criteria andFirstChapterIsNull() {
			addCriterion("first_chapter is null");
			return (Criteria) this;
		}

		public Criteria andFirstChapterIsNotNull() {
			addCriterion("first_chapter is not null");
			return (Criteria) this;
		}

		public Criteria andFirstChapterEqualTo(String value) {
			addCriterion("first_chapter =", value, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterNotEqualTo(String value) {
			addCriterion("first_chapter <>", value, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterGreaterThan(String value) {
			addCriterion("first_chapter >", value, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterGreaterThanOrEqualTo(String value) {
			addCriterion("first_chapter >=", value, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterLessThan(String value) {
			addCriterion("first_chapter <", value, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterLessThanOrEqualTo(String value) {
			addCriterion("first_chapter <=", value, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterLike(String value) {
			addCriterion("first_chapter like", value, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterNotLike(String value) {
			addCriterion("first_chapter not like", value, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterIn(List<String> values) {
			addCriterion("first_chapter in", values, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterNotIn(List<String> values) {
			addCriterion("first_chapter not in", values, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterBetween(String value1, String value2) {
			addCriterion("first_chapter between", value1, value2, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andFirstChapterNotBetween(String value1, String value2) {
			addCriterion("first_chapter not between", value1, value2, "firstChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterIsNull() {
			addCriterion("second_chapter is null");
			return (Criteria) this;
		}

		public Criteria andSecondChapterIsNotNull() {
			addCriterion("second_chapter is not null");
			return (Criteria) this;
		}

		public Criteria andSecondChapterEqualTo(String value) {
			addCriterion("second_chapter =", value, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterNotEqualTo(String value) {
			addCriterion("second_chapter <>", value, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterGreaterThan(String value) {
			addCriterion("second_chapter >", value, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterGreaterThanOrEqualTo(String value) {
			addCriterion("second_chapter >=", value, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterLessThan(String value) {
			addCriterion("second_chapter <", value, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterLessThanOrEqualTo(String value) {
			addCriterion("second_chapter <=", value, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterLike(String value) {
			addCriterion("second_chapter like", value, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterNotLike(String value) {
			addCriterion("second_chapter not like", value, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterIn(List<String> values) {
			addCriterion("second_chapter in", values, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterNotIn(List<String> values) {
			addCriterion("second_chapter not in", values, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterBetween(String value1, String value2) {
			addCriterion("second_chapter between", value1, value2, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andSecondChapterNotBetween(String value1, String value2) {
			addCriterion("second_chapter not between", value1, value2, "secondChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterIsNull() {
			addCriterion("three_chapter is null");
			return (Criteria) this;
		}

		public Criteria andThreeChapterIsNotNull() {
			addCriterion("three_chapter is not null");
			return (Criteria) this;
		}

		public Criteria andThreeChapterEqualTo(String value) {
			addCriterion("three_chapter =", value, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterNotEqualTo(String value) {
			addCriterion("three_chapter <>", value, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterGreaterThan(String value) {
			addCriterion("three_chapter >", value, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterGreaterThanOrEqualTo(String value) {
			addCriterion("three_chapter >=", value, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterLessThan(String value) {
			addCriterion("three_chapter <", value, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterLessThanOrEqualTo(String value) {
			addCriterion("three_chapter <=", value, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterLike(String value) {
			addCriterion("three_chapter like", value, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterNotLike(String value) {
			addCriterion("three_chapter not like", value, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterIn(List<String> values) {
			addCriterion("three_chapter in", values, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterNotIn(List<String> values) {
			addCriterion("three_chapter not in", values, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterBetween(String value1, String value2) {
			addCriterion("three_chapter between", value1, value2, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andThreeChapterNotBetween(String value1, String value2) {
			addCriterion("three_chapter not between", value1, value2, "threeChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterIsNull() {
			addCriterion("four_chapter is null");
			return (Criteria) this;
		}

		public Criteria andFourChapterIsNotNull() {
			addCriterion("four_chapter is not null");
			return (Criteria) this;
		}

		public Criteria andFourChapterEqualTo(String value) {
			addCriterion("four_chapter =", value, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterNotEqualTo(String value) {
			addCriterion("four_chapter <>", value, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterGreaterThan(String value) {
			addCriterion("four_chapter >", value, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterGreaterThanOrEqualTo(String value) {
			addCriterion("four_chapter >=", value, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterLessThan(String value) {
			addCriterion("four_chapter <", value, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterLessThanOrEqualTo(String value) {
			addCriterion("four_chapter <=", value, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterLike(String value) {
			addCriterion("four_chapter like", value, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterNotLike(String value) {
			addCriterion("four_chapter not like", value, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterIn(List<String> values) {
			addCriterion("four_chapter in", values, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterNotIn(List<String> values) {
			addCriterion("four_chapter not in", values, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterBetween(String value1, String value2) {
			addCriterion("four_chapter between", value1, value2, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andFourChapterNotBetween(String value1, String value2) {
			addCriterion("four_chapter not between", value1, value2, "fourChapter");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("`type` is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("`type` is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("`type` =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("`type` <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("`type` >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("`type` >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("`type` <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("`type` <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("`type` like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("`type` not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("`type` in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("`type` not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("`type` between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("`type` not between", value1, value2, "type");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pdf_code_chapter
	 * @mbggenerated  Wed Sep 20 18:21:18 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdf_code_chapter
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 19 16:18:40 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}