package com.kf.data.mybatis.entity;

public class PdfCodeTemporary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.pdf_type
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private String pdfType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.table_name
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.property
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.property_name
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private String propertyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.begin_position
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private String beginPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.end_position
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private String endPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.code_type
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private Integer codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.rank
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.md5
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.text_length
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private Integer textLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.group_id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_code_temporary.order_id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.id
     *
     * @return the value of pdf_code_temporary.id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.id
     *
     * @param id the value for pdf_code_temporary.id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.pdf_type
     *
     * @return the value of pdf_code_temporary.pdf_type
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public String getPdfType() {
        return pdfType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.pdf_type
     *
     * @param pdfType the value for pdf_code_temporary.pdf_type
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setPdfType(String pdfType) {
        this.pdfType = pdfType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.table_name
     *
     * @return the value of pdf_code_temporary.table_name
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.table_name
     *
     * @param tableName the value for pdf_code_temporary.table_name
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.property
     *
     * @return the value of pdf_code_temporary.property
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.property
     *
     * @param property the value for pdf_code_temporary.property
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setProperty(String property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.property_name
     *
     * @return the value of pdf_code_temporary.property_name
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.property_name
     *
     * @param propertyName the value for pdf_code_temporary.property_name
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.begin_position
     *
     * @return the value of pdf_code_temporary.begin_position
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public String getBeginPosition() {
        return beginPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.begin_position
     *
     * @param beginPosition the value for pdf_code_temporary.begin_position
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setBeginPosition(String beginPosition) {
        this.beginPosition = beginPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.end_position
     *
     * @return the value of pdf_code_temporary.end_position
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public String getEndPosition() {
        return endPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.end_position
     *
     * @param endPosition the value for pdf_code_temporary.end_position
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setEndPosition(String endPosition) {
        this.endPosition = endPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.code_type
     *
     * @return the value of pdf_code_temporary.code_type
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public Integer getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.code_type
     *
     * @param codeType the value for pdf_code_temporary.code_type
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setCodeType(Integer codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.rank
     *
     * @return the value of pdf_code_temporary.rank
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.rank
     *
     * @param rank the value for pdf_code_temporary.rank
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.md5
     *
     * @return the value of pdf_code_temporary.md5
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.md5
     *
     * @param md5 the value for pdf_code_temporary.md5
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.text_length
     *
     * @return the value of pdf_code_temporary.text_length
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public Integer getTextLength() {
        return textLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.text_length
     *
     * @param textLength the value for pdf_code_temporary.text_length
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setTextLength(Integer textLength) {
        this.textLength = textLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.group_id
     *
     * @return the value of pdf_code_temporary.group_id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.group_id
     *
     * @param groupId the value for pdf_code_temporary.group_id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_code_temporary.order_id
     *
     * @return the value of pdf_code_temporary.order_id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_code_temporary.order_id
     *
     * @param orderId the value for pdf_code_temporary.order_id
     *
     * @mbggenerated Mon Sep 18 16:39:19 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}