package com.kf.data.mybatis.entity;

import java.util.Date;

public class PdfReportLinks {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.pdf_type
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private String pdfType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.link
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.rank
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private Integer rank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.pdf_link
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private String pdfLink;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.title
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.company_name
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.notice_id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private Integer noticeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.publish_date
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private String publishDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.report_date
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private Date reportDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdf_report_links.company_id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	private Integer companyId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.id
	 * @return  the value of pdf_report_links.id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.id
	 * @param id  the value for pdf_report_links.id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.pdf_type
	 * @return  the value of pdf_report_links.pdf_type
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public String getPdfType() {
		return pdfType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.pdf_type
	 * @param pdfType  the value for pdf_report_links.pdf_type
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setPdfType(String pdfType) {
		this.pdfType = pdfType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.link
	 * @return  the value of pdf_report_links.link
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.link
	 * @param link  the value for pdf_report_links.link
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.rank
	 * @return  the value of pdf_report_links.rank
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public Integer getRank() {
		return rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.rank
	 * @param rank  the value for pdf_report_links.rank
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setRank(Integer rank) {
		this.rank = rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.pdf_link
	 * @return  the value of pdf_report_links.pdf_link
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public String getPdfLink() {
		return pdfLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.pdf_link
	 * @param pdfLink  the value for pdf_report_links.pdf_link
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setPdfLink(String pdfLink) {
		this.pdfLink = pdfLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.title
	 * @return  the value of pdf_report_links.title
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.title
	 * @param title  the value for pdf_report_links.title
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.company_name
	 * @return  the value of pdf_report_links.company_name
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.company_name
	 * @param companyName  the value for pdf_report_links.company_name
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.notice_id
	 * @return  the value of pdf_report_links.notice_id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public Integer getNoticeId() {
		return noticeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.notice_id
	 * @param noticeId  the value for pdf_report_links.notice_id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.publish_date
	 * @return  the value of pdf_report_links.publish_date
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public String getPublishDate() {
		return publishDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.publish_date
	 * @param publishDate  the value for pdf_report_links.publish_date
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setPublishDate(String publishDate) {
		this.publishDate = publishDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.report_date
	 * @return  the value of pdf_report_links.report_date
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public Date getReportDate() {
		return reportDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.report_date
	 * @param reportDate  the value for pdf_report_links.report_date
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdf_report_links.company_id
	 * @return  the value of pdf_report_links.company_id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public Integer getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdf_report_links.company_id
	 * @param companyId  the value for pdf_report_links.company_id
	 * @mbggenerated  Thu Sep 07 17:30:56 CST 2017
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
}