package com.kf.data.mybatis.entity;

import java.util.Date;

public class TycCompanyCheckCrawler {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.id
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.company_id
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.company_name
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.date
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.check_agency
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private String checkAgency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.type
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.result
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.status
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.created_at
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_check.updated_at
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.id
     *
     * @return the value of tyc_company_check.id
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.id
     *
     * @param id the value for tyc_company_check.id
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.company_id
     *
     * @return the value of tyc_company_check.company_id
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.company_id
     *
     * @param companyId the value for tyc_company_check.company_id
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.company_name
     *
     * @return the value of tyc_company_check.company_name
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.company_name
     *
     * @param companyName the value for tyc_company_check.company_name
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.date
     *
     * @return the value of tyc_company_check.date
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.date
     *
     * @param date the value for tyc_company_check.date
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.check_agency
     *
     * @return the value of tyc_company_check.check_agency
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public String getCheckAgency() {
        return checkAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.check_agency
     *
     * @param checkAgency the value for tyc_company_check.check_agency
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setCheckAgency(String checkAgency) {
        this.checkAgency = checkAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.type
     *
     * @return the value of tyc_company_check.type
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.type
     *
     * @param type the value for tyc_company_check.type
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.result
     *
     * @return the value of tyc_company_check.result
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.result
     *
     * @param result the value for tyc_company_check.result
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.status
     *
     * @return the value of tyc_company_check.status
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.status
     *
     * @param status the value for tyc_company_check.status
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.created_at
     *
     * @return the value of tyc_company_check.created_at
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.created_at
     *
     * @param createdAt the value for tyc_company_check.created_at
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_check.updated_at
     *
     * @return the value of tyc_company_check.updated_at
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_check.updated_at
     *
     * @param updatedAt the value for tyc_company_check.updated_at
     *
     * @mbggenerated Tue Oct 31 15:41:18 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}