package com.kf.data.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TycCompanyImExPortCrawlerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public TycCompanyImExPortCrawlerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIsNull() {
            addCriterion("register_date is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIsNotNull() {
            addCriterion("register_date is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDateEqualTo(String value) {
            addCriterion("register_date =", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotEqualTo(String value) {
            addCriterion("register_date <>", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateGreaterThan(String value) {
            addCriterion("register_date >", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateGreaterThanOrEqualTo(String value) {
            addCriterion("register_date >=", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLessThan(String value) {
            addCriterion("register_date <", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLessThanOrEqualTo(String value) {
            addCriterion("register_date <=", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLike(String value) {
            addCriterion("register_date like", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotLike(String value) {
            addCriterion("register_date not like", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIn(List<String> values) {
            addCriterion("register_date in", values, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotIn(List<String> values) {
            addCriterion("register_date not in", values, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateBetween(String value1, String value2) {
            addCriterion("register_date between", value1, value2, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotBetween(String value1, String value2) {
            addCriterion("register_date not between", value1, value2, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIsNull() {
            addCriterion("register_number is null");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIsNotNull() {
            addCriterion("register_number is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberEqualTo(String value) {
            addCriterion("register_number =", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotEqualTo(String value) {
            addCriterion("register_number <>", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberGreaterThan(String value) {
            addCriterion("register_number >", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberGreaterThanOrEqualTo(String value) {
            addCriterion("register_number >=", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberLessThan(String value) {
            addCriterion("register_number <", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberLessThanOrEqualTo(String value) {
            addCriterion("register_number <=", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberLike(String value) {
            addCriterion("register_number like", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotLike(String value) {
            addCriterion("register_number not like", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIn(List<String> values) {
            addCriterion("register_number in", values, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotIn(List<String> values) {
            addCriterion("register_number not in", values, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberBetween(String value1, String value2) {
            addCriterion("register_number between", value1, value2, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotBetween(String value1, String value2) {
            addCriterion("register_number not between", value1, value2, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgIsNull() {
            addCriterion("register_org is null");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgIsNotNull() {
            addCriterion("register_org is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgEqualTo(String value) {
            addCriterion("register_org =", value, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgNotEqualTo(String value) {
            addCriterion("register_org <>", value, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgGreaterThan(String value) {
            addCriterion("register_org >", value, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgGreaterThanOrEqualTo(String value) {
            addCriterion("register_org >=", value, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgLessThan(String value) {
            addCriterion("register_org <", value, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgLessThanOrEqualTo(String value) {
            addCriterion("register_org <=", value, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgLike(String value) {
            addCriterion("register_org like", value, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgNotLike(String value) {
            addCriterion("register_org not like", value, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgIn(List<String> values) {
            addCriterion("register_org in", values, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgNotIn(List<String> values) {
            addCriterion("register_org not in", values, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgBetween(String value1, String value2) {
            addCriterion("register_org between", value1, value2, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andRegisterOrgNotBetween(String value1, String value2) {
            addCriterion("register_org not between", value1, value2, "registerOrg");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsIsNull() {
            addCriterion("admin_precincts is null");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsIsNotNull() {
            addCriterion("admin_precincts is not null");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsEqualTo(String value) {
            addCriterion("admin_precincts =", value, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsNotEqualTo(String value) {
            addCriterion("admin_precincts <>", value, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsGreaterThan(String value) {
            addCriterion("admin_precincts >", value, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsGreaterThanOrEqualTo(String value) {
            addCriterion("admin_precincts >=", value, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsLessThan(String value) {
            addCriterion("admin_precincts <", value, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsLessThanOrEqualTo(String value) {
            addCriterion("admin_precincts <=", value, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsLike(String value) {
            addCriterion("admin_precincts like", value, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsNotLike(String value) {
            addCriterion("admin_precincts not like", value, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsIn(List<String> values) {
            addCriterion("admin_precincts in", values, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsNotIn(List<String> values) {
            addCriterion("admin_precincts not in", values, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsBetween(String value1, String value2) {
            addCriterion("admin_precincts between", value1, value2, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andAdminPrecinctsNotBetween(String value1, String value2) {
            addCriterion("admin_precincts not between", value1, value2, "adminPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsIsNull() {
            addCriterion("economy_precincts is null");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsIsNotNull() {
            addCriterion("economy_precincts is not null");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsEqualTo(String value) {
            addCriterion("economy_precincts =", value, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsNotEqualTo(String value) {
            addCriterion("economy_precincts <>", value, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsGreaterThan(String value) {
            addCriterion("economy_precincts >", value, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsGreaterThanOrEqualTo(String value) {
            addCriterion("economy_precincts >=", value, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsLessThan(String value) {
            addCriterion("economy_precincts <", value, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsLessThanOrEqualTo(String value) {
            addCriterion("economy_precincts <=", value, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsLike(String value) {
            addCriterion("economy_precincts like", value, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsNotLike(String value) {
            addCriterion("economy_precincts not like", value, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsIn(List<String> values) {
            addCriterion("economy_precincts in", values, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsNotIn(List<String> values) {
            addCriterion("economy_precincts not in", values, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsBetween(String value1, String value2) {
            addCriterion("economy_precincts between", value1, value2, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andEconomyPrecinctsNotBetween(String value1, String value2) {
            addCriterion("economy_precincts not between", value1, value2, "economyPrecincts");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNull() {
            addCriterion("operate_type is null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNotNull() {
            addCriterion("operate_type is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeEqualTo(String value) {
            addCriterion("operate_type =", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotEqualTo(String value) {
            addCriterion("operate_type <>", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThan(String value) {
            addCriterion("operate_type >", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("operate_type >=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThan(String value) {
            addCriterion("operate_type <", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThanOrEqualTo(String value) {
            addCriterion("operate_type <=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLike(String value) {
            addCriterion("operate_type like", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotLike(String value) {
            addCriterion("operate_type not like", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIn(List<String> values) {
            addCriterion("operate_type in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotIn(List<String> values) {
            addCriterion("operate_type not in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeBetween(String value1, String value2) {
            addCriterion("operate_type between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotBetween(String value1, String value2) {
            addCriterion("operate_type not between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsIsNull() {
            addCriterion("special_precincts is null");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsIsNotNull() {
            addCriterion("special_precincts is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsEqualTo(String value) {
            addCriterion("special_precincts =", value, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsNotEqualTo(String value) {
            addCriterion("special_precincts <>", value, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsGreaterThan(String value) {
            addCriterion("special_precincts >", value, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsGreaterThanOrEqualTo(String value) {
            addCriterion("special_precincts >=", value, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsLessThan(String value) {
            addCriterion("special_precincts <", value, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsLessThanOrEqualTo(String value) {
            addCriterion("special_precincts <=", value, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsLike(String value) {
            addCriterion("special_precincts like", value, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsNotLike(String value) {
            addCriterion("special_precincts not like", value, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsIn(List<String> values) {
            addCriterion("special_precincts in", values, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsNotIn(List<String> values) {
            addCriterion("special_precincts not in", values, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsBetween(String value1, String value2) {
            addCriterion("special_precincts between", value1, value2, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andSpecialPrecinctsNotBetween(String value1, String value2) {
            addCriterion("special_precincts not between", value1, value2, "specialPrecincts");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeIsNull() {
            addCriterion("industry_type is null");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeIsNotNull() {
            addCriterion("industry_type is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeEqualTo(String value) {
            addCriterion("industry_type =", value, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeNotEqualTo(String value) {
            addCriterion("industry_type <>", value, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeGreaterThan(String value) {
            addCriterion("industry_type >", value, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeGreaterThanOrEqualTo(String value) {
            addCriterion("industry_type >=", value, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeLessThan(String value) {
            addCriterion("industry_type <", value, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeLessThanOrEqualTo(String value) {
            addCriterion("industry_type <=", value, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeLike(String value) {
            addCriterion("industry_type like", value, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeNotLike(String value) {
            addCriterion("industry_type not like", value, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeIn(List<String> values) {
            addCriterion("industry_type in", values, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeNotIn(List<String> values) {
            addCriterion("industry_type not in", values, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeBetween(String value1, String value2) {
            addCriterion("industry_type between", value1, value2, "industryType");
            return (Criteria) this;
        }

        public Criteria andIndustryTypeNotBetween(String value1, String value2) {
            addCriterion("industry_type not between", value1, value2, "industryType");
            return (Criteria) this;
        }

        public Criteria andDeclareDateIsNull() {
            addCriterion("declare_date is null");
            return (Criteria) this;
        }

        public Criteria andDeclareDateIsNotNull() {
            addCriterion("declare_date is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareDateEqualTo(Date value) {
            addCriterion("declare_date =", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateNotEqualTo(Date value) {
            addCriterion("declare_date <>", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateGreaterThan(Date value) {
            addCriterion("declare_date >", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateGreaterThanOrEqualTo(Date value) {
            addCriterion("declare_date >=", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateLessThan(Date value) {
            addCriterion("declare_date <", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateLessThanOrEqualTo(Date value) {
            addCriterion("declare_date <=", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateIn(List<Date> values) {
            addCriterion("declare_date in", values, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateNotIn(List<Date> values) {
            addCriterion("declare_date not in", values, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateBetween(Date value1, Date value2) {
            addCriterion("declare_date between", value1, value2, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateNotBetween(Date value1, Date value2) {
            addCriterion("declare_date not between", value1, value2, "declareDate");
            return (Criteria) this;
        }

        public Criteria andIdentifierIsNull() {
            addCriterion("identifier is null");
            return (Criteria) this;
        }

        public Criteria andIdentifierIsNotNull() {
            addCriterion("identifier is not null");
            return (Criteria) this;
        }

        public Criteria andIdentifierEqualTo(String value) {
            addCriterion("identifier =", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotEqualTo(String value) {
            addCriterion("identifier <>", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierGreaterThan(String value) {
            addCriterion("identifier >", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("identifier >=", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLessThan(String value) {
            addCriterion("identifier <", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLessThanOrEqualTo(String value) {
            addCriterion("identifier <=", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLike(String value) {
            addCriterion("identifier like", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotLike(String value) {
            addCriterion("identifier not like", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierIn(List<String> values) {
            addCriterion("identifier in", values, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotIn(List<String> values) {
            addCriterion("identifier not in", values, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierBetween(String value1, String value2) {
            addCriterion("identifier between", value1, value2, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotBetween(String value1, String value2) {
            addCriterion("identifier not between", value1, value2, "identifier");
            return (Criteria) this;
        }

        public Criteria andReportStatusIsNull() {
            addCriterion("report_status is null");
            return (Criteria) this;
        }

        public Criteria andReportStatusIsNotNull() {
            addCriterion("report_status is not null");
            return (Criteria) this;
        }

        public Criteria andReportStatusEqualTo(String value) {
            addCriterion("report_status =", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusNotEqualTo(String value) {
            addCriterion("report_status <>", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusGreaterThan(String value) {
            addCriterion("report_status >", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusGreaterThanOrEqualTo(String value) {
            addCriterion("report_status >=", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusLessThan(String value) {
            addCriterion("report_status <", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusLessThanOrEqualTo(String value) {
            addCriterion("report_status <=", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusLike(String value) {
            addCriterion("report_status like", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusNotLike(String value) {
            addCriterion("report_status not like", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusIn(List<String> values) {
            addCriterion("report_status in", values, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusNotIn(List<String> values) {
            addCriterion("report_status not in", values, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusBetween(String value1, String value2) {
            addCriterion("report_status between", value1, value2, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusNotBetween(String value1, String value2) {
            addCriterion("report_status not between", value1, value2, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeIsNull() {
            addCriterion("electronic_type is null");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeIsNotNull() {
            addCriterion("electronic_type is not null");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeEqualTo(String value) {
            addCriterion("electronic_type =", value, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeNotEqualTo(String value) {
            addCriterion("electronic_type <>", value, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeGreaterThan(String value) {
            addCriterion("electronic_type >", value, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeGreaterThanOrEqualTo(String value) {
            addCriterion("electronic_type >=", value, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeLessThan(String value) {
            addCriterion("electronic_type <", value, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeLessThanOrEqualTo(String value) {
            addCriterion("electronic_type <=", value, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeLike(String value) {
            addCriterion("electronic_type like", value, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeNotLike(String value) {
            addCriterion("electronic_type not like", value, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeIn(List<String> values) {
            addCriterion("electronic_type in", values, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeNotIn(List<String> values) {
            addCriterion("electronic_type not in", values, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeBetween(String value1, String value2) {
            addCriterion("electronic_type between", value1, value2, "electronicType");
            return (Criteria) this;
        }

        public Criteria andElectronicTypeNotBetween(String value1, String value2) {
            addCriterion("electronic_type not between", value1, value2, "electronicType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 30 13:38:40 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tyc_company_im_ex_port
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}