package com.kf.data.mybatis.entity;

import java.util.Date;

public class TycCompanySfpmCrawler {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.auction_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String auctionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.auction_date
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Date auctionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.auction_org
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String auctionOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.company_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.company_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.status
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.created_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.updated_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.start_price
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Double startPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.valuation
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Double valuation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.detail_link
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String detailLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_sfpm.goods
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String goods;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.id
     *
     * @return the value of tyc_company_sfpm.id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.id
     *
     * @param id the value for tyc_company_sfpm.id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.auction_name
     *
     * @return the value of tyc_company_sfpm.auction_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getAuctionName() {
        return auctionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.auction_name
     *
     * @param auctionName the value for tyc_company_sfpm.auction_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setAuctionName(String auctionName) {
        this.auctionName = auctionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.auction_date
     *
     * @return the value of tyc_company_sfpm.auction_date
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Date getAuctionDate() {
        return auctionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.auction_date
     *
     * @param auctionDate the value for tyc_company_sfpm.auction_date
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setAuctionDate(Date auctionDate) {
        this.auctionDate = auctionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.auction_org
     *
     * @return the value of tyc_company_sfpm.auction_org
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getAuctionOrg() {
        return auctionOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.auction_org
     *
     * @param auctionOrg the value for tyc_company_sfpm.auction_org
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setAuctionOrg(String auctionOrg) {
        this.auctionOrg = auctionOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.company_id
     *
     * @return the value of tyc_company_sfpm.company_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.company_id
     *
     * @param companyId the value for tyc_company_sfpm.company_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.company_name
     *
     * @return the value of tyc_company_sfpm.company_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.company_name
     *
     * @param companyName the value for tyc_company_sfpm.company_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.status
     *
     * @return the value of tyc_company_sfpm.status
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.status
     *
     * @param status the value for tyc_company_sfpm.status
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.created_at
     *
     * @return the value of tyc_company_sfpm.created_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.created_at
     *
     * @param createdAt the value for tyc_company_sfpm.created_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.updated_at
     *
     * @return the value of tyc_company_sfpm.updated_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.updated_at
     *
     * @param updatedAt the value for tyc_company_sfpm.updated_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.start_price
     *
     * @return the value of tyc_company_sfpm.start_price
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Double getStartPrice() {
        return startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.start_price
     *
     * @param startPrice the value for tyc_company_sfpm.start_price
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setStartPrice(Double startPrice) {
        this.startPrice = startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.valuation
     *
     * @return the value of tyc_company_sfpm.valuation
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Double getValuation() {
        return valuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.valuation
     *
     * @param valuation the value for tyc_company_sfpm.valuation
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setValuation(Double valuation) {
        this.valuation = valuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.detail_link
     *
     * @return the value of tyc_company_sfpm.detail_link
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getDetailLink() {
        return detailLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.detail_link
     *
     * @param detailLink the value for tyc_company_sfpm.detail_link
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setDetailLink(String detailLink) {
        this.detailLink = detailLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_sfpm.goods
     *
     * @return the value of tyc_company_sfpm.goods
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_sfpm.goods
     *
     * @param goods the value for tyc_company_sfpm.goods
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setGoods(String goods) {
        this.goods = goods;
    }
}