package com.kf.data.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TycCompanyDomainRecordCrawlerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public TycCompanyDomainRecordCrawlerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdEqualTo(String value) {
			addCriterion("company_id =", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotEqualTo(String value) {
			addCriterion("company_id <>", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThan(String value) {
			addCriterion("company_id >", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
			addCriterion("company_id >=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThan(String value) {
			addCriterion("company_id <", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(String value) {
			addCriterion("company_id <=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLike(String value) {
			addCriterion("company_id like", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotLike(String value) {
			addCriterion("company_id not like", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIn(List<String> values) {
			addCriterion("company_id in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotIn(List<String> values) {
			addCriterion("company_id not in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdBetween(String value1, String value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotBetween(String value1, String value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNull() {
			addCriterion("company_name is null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNotNull() {
			addCriterion("company_name is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameEqualTo(String value) {
			addCriterion("company_name =", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotEqualTo(String value) {
			addCriterion("company_name <>", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThan(String value) {
			addCriterion("company_name >", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
			addCriterion("company_name >=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThan(String value) {
			addCriterion("company_name <", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThanOrEqualTo(String value) {
			addCriterion("company_name <=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLike(String value) {
			addCriterion("company_name like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotLike(String value) {
			addCriterion("company_name not like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIn(List<String> values) {
			addCriterion("company_name in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotIn(List<String> values) {
			addCriterion("company_name not in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameBetween(String value1, String value2) {
			addCriterion("company_name between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotBetween(String value1, String value2) {
			addCriterion("company_name not between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andDomainIsNull() {
			addCriterion("`domain` is null");
			return (Criteria) this;
		}

		public Criteria andDomainIsNotNull() {
			addCriterion("`domain` is not null");
			return (Criteria) this;
		}

		public Criteria andDomainEqualTo(String value) {
			addCriterion("`domain` =", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotEqualTo(String value) {
			addCriterion("`domain` <>", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainGreaterThan(String value) {
			addCriterion("`domain` >", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainGreaterThanOrEqualTo(String value) {
			addCriterion("`domain` >=", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLessThan(String value) {
			addCriterion("`domain` <", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLessThanOrEqualTo(String value) {
			addCriterion("`domain` <=", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLike(String value) {
			addCriterion("`domain` like", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotLike(String value) {
			addCriterion("`domain` not like", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainIn(List<String> values) {
			addCriterion("`domain` in", values, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotIn(List<String> values) {
			addCriterion("`domain` not in", values, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainBetween(String value1, String value2) {
			addCriterion("`domain` between", value1, value2, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotBetween(String value1, String value2) {
			addCriterion("`domain` not between", value1, value2, "domain");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineIsNull() {
			addCriterion("release_date_machine is null");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineIsNotNull() {
			addCriterion("release_date_machine is not null");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineEqualTo(Integer value) {
			addCriterion("release_date_machine =", value, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineNotEqualTo(Integer value) {
			addCriterion("release_date_machine <>", value, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineGreaterThan(Integer value) {
			addCriterion("release_date_machine >", value, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineGreaterThanOrEqualTo(Integer value) {
			addCriterion("release_date_machine >=", value, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineLessThan(Integer value) {
			addCriterion("release_date_machine <", value, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineLessThanOrEqualTo(Integer value) {
			addCriterion("release_date_machine <=", value, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineIn(List<Integer> values) {
			addCriterion("release_date_machine in", values, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineNotIn(List<Integer> values) {
			addCriterion("release_date_machine not in", values, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineBetween(Integer value1, Integer value2) {
			addCriterion("release_date_machine between", value1, value2, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateMachineNotBetween(Integer value1, Integer value2) {
			addCriterion("release_date_machine not between", value1, value2, "releaseDateMachine");
			return (Criteria) this;
		}

		public Criteria andReleaseDateIsNull() {
			addCriterion("release_date is null");
			return (Criteria) this;
		}

		public Criteria andReleaseDateIsNotNull() {
			addCriterion("release_date is not null");
			return (Criteria) this;
		}

		public Criteria andReleaseDateEqualTo(String value) {
			addCriterion("release_date =", value, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateNotEqualTo(String value) {
			addCriterion("release_date <>", value, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateGreaterThan(String value) {
			addCriterion("release_date >", value, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateGreaterThanOrEqualTo(String value) {
			addCriterion("release_date >=", value, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateLessThan(String value) {
			addCriterion("release_date <", value, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateLessThanOrEqualTo(String value) {
			addCriterion("release_date <=", value, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateLike(String value) {
			addCriterion("release_date like", value, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateNotLike(String value) {
			addCriterion("release_date not like", value, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateIn(List<String> values) {
			addCriterion("release_date in", values, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateNotIn(List<String> values) {
			addCriterion("release_date not in", values, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateBetween(String value1, String value2) {
			addCriterion("release_date between", value1, value2, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andReleaseDateNotBetween(String value1, String value2) {
			addCriterion("release_date not between", value1, value2, "releaseDate");
			return (Criteria) this;
		}

		public Criteria andHostIdIsNull() {
			addCriterion("host_id is null");
			return (Criteria) this;
		}

		public Criteria andHostIdIsNotNull() {
			addCriterion("host_id is not null");
			return (Criteria) this;
		}

		public Criteria andHostIdEqualTo(String value) {
			addCriterion("host_id =", value, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdNotEqualTo(String value) {
			addCriterion("host_id <>", value, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdGreaterThan(String value) {
			addCriterion("host_id >", value, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdGreaterThanOrEqualTo(String value) {
			addCriterion("host_id >=", value, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdLessThan(String value) {
			addCriterion("host_id <", value, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdLessThanOrEqualTo(String value) {
			addCriterion("host_id <=", value, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdLike(String value) {
			addCriterion("host_id like", value, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdNotLike(String value) {
			addCriterion("host_id not like", value, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdIn(List<String> values) {
			addCriterion("host_id in", values, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdNotIn(List<String> values) {
			addCriterion("host_id not in", values, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdBetween(String value1, String value2) {
			addCriterion("host_id between", value1, value2, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostIdNotBetween(String value1, String value2) {
			addCriterion("host_id not between", value1, value2, "hostId");
			return (Criteria) this;
		}

		public Criteria andHostNameIsNull() {
			addCriterion("host_name is null");
			return (Criteria) this;
		}

		public Criteria andHostNameIsNotNull() {
			addCriterion("host_name is not null");
			return (Criteria) this;
		}

		public Criteria andHostNameEqualTo(String value) {
			addCriterion("host_name =", value, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameNotEqualTo(String value) {
			addCriterion("host_name <>", value, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameGreaterThan(String value) {
			addCriterion("host_name >", value, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameGreaterThanOrEqualTo(String value) {
			addCriterion("host_name >=", value, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameLessThan(String value) {
			addCriterion("host_name <", value, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameLessThanOrEqualTo(String value) {
			addCriterion("host_name <=", value, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameLike(String value) {
			addCriterion("host_name like", value, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameNotLike(String value) {
			addCriterion("host_name not like", value, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameIn(List<String> values) {
			addCriterion("host_name in", values, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameNotIn(List<String> values) {
			addCriterion("host_name not in", values, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameBetween(String value1, String value2) {
			addCriterion("host_name between", value1, value2, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostNameNotBetween(String value1, String value2) {
			addCriterion("host_name not between", value1, value2, "hostName");
			return (Criteria) this;
		}

		public Criteria andHostTypeIsNull() {
			addCriterion("host_type is null");
			return (Criteria) this;
		}

		public Criteria andHostTypeIsNotNull() {
			addCriterion("host_type is not null");
			return (Criteria) this;
		}

		public Criteria andHostTypeEqualTo(String value) {
			addCriterion("host_type =", value, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeNotEqualTo(String value) {
			addCriterion("host_type <>", value, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeGreaterThan(String value) {
			addCriterion("host_type >", value, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeGreaterThanOrEqualTo(String value) {
			addCriterion("host_type >=", value, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeLessThan(String value) {
			addCriterion("host_type <", value, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeLessThanOrEqualTo(String value) {
			addCriterion("host_type <=", value, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeLike(String value) {
			addCriterion("host_type like", value, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeNotLike(String value) {
			addCriterion("host_type not like", value, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeIn(List<String> values) {
			addCriterion("host_type in", values, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeNotIn(List<String> values) {
			addCriterion("host_type not in", values, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeBetween(String value1, String value2) {
			addCriterion("host_type between", value1, value2, "hostType");
			return (Criteria) this;
		}

		public Criteria andHostTypeNotBetween(String value1, String value2) {
			addCriterion("host_type not between", value1, value2, "hostType");
			return (Criteria) this;
		}

		public Criteria andRecordNumberIsNull() {
			addCriterion("record_number is null");
			return (Criteria) this;
		}

		public Criteria andRecordNumberIsNotNull() {
			addCriterion("record_number is not null");
			return (Criteria) this;
		}

		public Criteria andRecordNumberEqualTo(String value) {
			addCriterion("record_number =", value, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberNotEqualTo(String value) {
			addCriterion("record_number <>", value, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberGreaterThan(String value) {
			addCriterion("record_number >", value, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberGreaterThanOrEqualTo(String value) {
			addCriterion("record_number >=", value, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberLessThan(String value) {
			addCriterion("record_number <", value, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberLessThanOrEqualTo(String value) {
			addCriterion("record_number <=", value, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberLike(String value) {
			addCriterion("record_number like", value, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberNotLike(String value) {
			addCriterion("record_number not like", value, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberIn(List<String> values) {
			addCriterion("record_number in", values, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberNotIn(List<String> values) {
			addCriterion("record_number not in", values, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberBetween(String value1, String value2) {
			addCriterion("record_number between", value1, value2, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andRecordNumberNotBetween(String value1, String value2) {
			addCriterion("record_number not between", value1, value2, "recordNumber");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIsNull() {
			addCriterion("home_url is null");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIsNotNull() {
			addCriterion("home_url is not null");
			return (Criteria) this;
		}

		public Criteria andHomeUrlEqualTo(String value) {
			addCriterion("home_url =", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotEqualTo(String value) {
			addCriterion("home_url <>", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlGreaterThan(String value) {
			addCriterion("home_url >", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlGreaterThanOrEqualTo(String value) {
			addCriterion("home_url >=", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLessThan(String value) {
			addCriterion("home_url <", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLessThanOrEqualTo(String value) {
			addCriterion("home_url <=", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLike(String value) {
			addCriterion("home_url like", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotLike(String value) {
			addCriterion("home_url not like", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIn(List<String> values) {
			addCriterion("home_url in", values, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotIn(List<String> values) {
			addCriterion("home_url not in", values, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlBetween(String value1, String value2) {
			addCriterion("home_url between", value1, value2, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotBetween(String value1, String value2) {
			addCriterion("home_url not between", value1, value2, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNull() {
			addCriterion("site_name is null");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNotNull() {
			addCriterion("site_name is not null");
			return (Criteria) this;
		}

		public Criteria andSiteNameEqualTo(String value) {
			addCriterion("site_name =", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotEqualTo(String value) {
			addCriterion("site_name <>", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThan(String value) {
			addCriterion("site_name >", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThanOrEqualTo(String value) {
			addCriterion("site_name >=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThan(String value) {
			addCriterion("site_name <", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThanOrEqualTo(String value) {
			addCriterion("site_name <=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLike(String value) {
			addCriterion("site_name like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotLike(String value) {
			addCriterion("site_name not like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameIn(List<String> values) {
			addCriterion("site_name in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotIn(List<String> values) {
			addCriterion("site_name not in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameBetween(String value1, String value2) {
			addCriterion("site_name between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotBetween(String value1, String value2) {
			addCriterion("site_name not between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusIsNull() {
			addCriterion("operating_status is null");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusIsNotNull() {
			addCriterion("operating_status is not null");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusEqualTo(String value) {
			addCriterion("operating_status =", value, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusNotEqualTo(String value) {
			addCriterion("operating_status <>", value, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusGreaterThan(String value) {
			addCriterion("operating_status >", value, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusGreaterThanOrEqualTo(String value) {
			addCriterion("operating_status >=", value, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusLessThan(String value) {
			addCriterion("operating_status <", value, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusLessThanOrEqualTo(String value) {
			addCriterion("operating_status <=", value, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusLike(String value) {
			addCriterion("operating_status like", value, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusNotLike(String value) {
			addCriterion("operating_status not like", value, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusIn(List<String> values) {
			addCriterion("operating_status in", values, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusNotIn(List<String> values) {
			addCriterion("operating_status not in", values, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusBetween(String value1, String value2) {
			addCriterion("operating_status between", value1, value2, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andOperatingStatusNotBetween(String value1, String value2) {
			addCriterion("operating_status not between", value1, value2, "operatingStatus");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("`status` is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("`status` is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Boolean value) {
			addCriterion("`status` =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Boolean value) {
			addCriterion("`status` <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Boolean value) {
			addCriterion("`status` >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
			addCriterion("`status` >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Boolean value) {
			addCriterion("`status` <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Boolean value) {
			addCriterion("`status` <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Boolean> values) {
			addCriterion("`status` in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Boolean> values) {
			addCriterion("`status` not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Boolean value1, Boolean value2) {
			addCriterion("`status` between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
			addCriterion("`status` not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tyc_company_domain_record
	 * @mbggenerated  Fri Sep 29 13:59:37 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tyc_company_domain_record
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 29 13:59:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}