package com.kf.data.mybatis.entity;

import java.util.Date;

public class TycCompanyCompetitorsCrawler {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.id
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.company_id
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.company_name
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.status
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.created_at
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.updated_at
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.competitor_logo
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String competitorLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.competitor_name
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String competitorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.area
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.turn
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String turn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.industry
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.scope
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.regtime
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_company_competitors.assessment_value
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    private String assessmentValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.id
     *
     * @return the value of tyc_company_competitors.id
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.id
     *
     * @param id the value for tyc_company_competitors.id
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.company_id
     *
     * @return the value of tyc_company_competitors.company_id
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.company_id
     *
     * @param companyId the value for tyc_company_competitors.company_id
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.company_name
     *
     * @return the value of tyc_company_competitors.company_name
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.company_name
     *
     * @param companyName the value for tyc_company_competitors.company_name
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.status
     *
     * @return the value of tyc_company_competitors.status
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.status
     *
     * @param status the value for tyc_company_competitors.status
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.created_at
     *
     * @return the value of tyc_company_competitors.created_at
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.created_at
     *
     * @param createdAt the value for tyc_company_competitors.created_at
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.updated_at
     *
     * @return the value of tyc_company_competitors.updated_at
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.updated_at
     *
     * @param updatedAt the value for tyc_company_competitors.updated_at
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.competitor_logo
     *
     * @return the value of tyc_company_competitors.competitor_logo
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getCompetitorLogo() {
        return competitorLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.competitor_logo
     *
     * @param competitorLogo the value for tyc_company_competitors.competitor_logo
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setCompetitorLogo(String competitorLogo) {
        this.competitorLogo = competitorLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.competitor_name
     *
     * @return the value of tyc_company_competitors.competitor_name
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getCompetitorName() {
        return competitorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.competitor_name
     *
     * @param competitorName the value for tyc_company_competitors.competitor_name
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setCompetitorName(String competitorName) {
        this.competitorName = competitorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.area
     *
     * @return the value of tyc_company_competitors.area
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.area
     *
     * @param area the value for tyc_company_competitors.area
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.turn
     *
     * @return the value of tyc_company_competitors.turn
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getTurn() {
        return turn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.turn
     *
     * @param turn the value for tyc_company_competitors.turn
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setTurn(String turn) {
        this.turn = turn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.industry
     *
     * @return the value of tyc_company_competitors.industry
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.industry
     *
     * @param industry the value for tyc_company_competitors.industry
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.scope
     *
     * @return the value of tyc_company_competitors.scope
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.scope
     *
     * @param scope the value for tyc_company_competitors.scope
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.regtime
     *
     * @return the value of tyc_company_competitors.regtime
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.regtime
     *
     * @param regtime the value for tyc_company_competitors.regtime
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setRegtime(String regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_company_competitors.assessment_value
     *
     * @return the value of tyc_company_competitors.assessment_value
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public String getAssessmentValue() {
        return assessmentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_company_competitors.assessment_value
     *
     * @param assessmentValue the value for tyc_company_competitors.assessment_value
     *
     * @mbggenerated Mon Oct 30 15:30:29 CST 2017
     */
    public void setAssessmentValue(String assessmentValue) {
        this.assessmentValue = assessmentValue;
    }
}