package com.kf.data.mybatis.entity;

import java.util.Date;

public class TycEventsTenderBidCrawler {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.id
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.title
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.date
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private String date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.status
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.created_at
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.updated_at
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.company_id
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private String companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.company_name
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.buyer
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private String buyer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tyc_events_tender_bid.content
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.id
	 * @return  the value of tyc_events_tender_bid.id
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.id
	 * @param id  the value for tyc_events_tender_bid.id
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.title
	 * @return  the value of tyc_events_tender_bid.title
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.title
	 * @param title  the value for tyc_events_tender_bid.title
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.date
	 * @return  the value of tyc_events_tender_bid.date
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public String getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.date
	 * @param date  the value for tyc_events_tender_bid.date
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.status
	 * @return  the value of tyc_events_tender_bid.status
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.status
	 * @param status  the value for tyc_events_tender_bid.status
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.created_at
	 * @return  the value of tyc_events_tender_bid.created_at
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.created_at
	 * @param createdAt  the value for tyc_events_tender_bid.created_at
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.updated_at
	 * @return  the value of tyc_events_tender_bid.updated_at
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.updated_at
	 * @param updatedAt  the value for tyc_events_tender_bid.updated_at
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.company_id
	 * @return  the value of tyc_events_tender_bid.company_id
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.company_id
	 * @param companyId  the value for tyc_events_tender_bid.company_id
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.company_name
	 * @return  the value of tyc_events_tender_bid.company_name
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.company_name
	 * @param companyName  the value for tyc_events_tender_bid.company_name
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.buyer
	 * @return  the value of tyc_events_tender_bid.buyer
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public String getBuyer() {
		return buyer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.buyer
	 * @param buyer  the value for tyc_events_tender_bid.buyer
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tyc_events_tender_bid.content
	 * @return  the value of tyc_events_tender_bid.content
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tyc_events_tender_bid.content
	 * @param content  the value for tyc_events_tender_bid.content
	 * @mbggenerated  Wed Nov 01 15:18:49 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}
}