package com.kf.data.mybatis.entity;

import java.util.Date;

public class TycEventsInvestInvestorsCrawler {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.event_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.event_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.investor_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String investorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.investor_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String investorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.invest_type
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String investType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.investor_type_code
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String investorTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.investor_type
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String investorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.investment_amount
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Double investmentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.invest_mode
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String investMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.direct_investor_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String directInvestorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.direct_investor_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String directInvestorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.investor_shortname
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String investorShortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.direct_investor_shortname
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private String directInvestorShortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.status
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.created_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tyc_events_invest_investors.updated_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.id
     *
     * @return the value of tyc_events_invest_investors.id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.id
     *
     * @param id the value for tyc_events_invest_investors.id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.event_id
     *
     * @return the value of tyc_events_invest_investors.event_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.event_id
     *
     * @param eventId the value for tyc_events_invest_investors.event_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.event_name
     *
     * @return the value of tyc_events_invest_investors.event_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.event_name
     *
     * @param eventName the value for tyc_events_invest_investors.event_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.investor_id
     *
     * @return the value of tyc_events_invest_investors.investor_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getInvestorId() {
        return investorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.investor_id
     *
     * @param investorId the value for tyc_events_invest_investors.investor_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setInvestorId(String investorId) {
        this.investorId = investorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.investor_name
     *
     * @return the value of tyc_events_invest_investors.investor_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getInvestorName() {
        return investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.investor_name
     *
     * @param investorName the value for tyc_events_invest_investors.investor_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setInvestorName(String investorName) {
        this.investorName = investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.invest_type
     *
     * @return the value of tyc_events_invest_investors.invest_type
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getInvestType() {
        return investType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.invest_type
     *
     * @param investType the value for tyc_events_invest_investors.invest_type
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setInvestType(String investType) {
        this.investType = investType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.investor_type_code
     *
     * @return the value of tyc_events_invest_investors.investor_type_code
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getInvestorTypeCode() {
        return investorTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.investor_type_code
     *
     * @param investorTypeCode the value for tyc_events_invest_investors.investor_type_code
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setInvestorTypeCode(String investorTypeCode) {
        this.investorTypeCode = investorTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.investor_type
     *
     * @return the value of tyc_events_invest_investors.investor_type
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getInvestorType() {
        return investorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.investor_type
     *
     * @param investorType the value for tyc_events_invest_investors.investor_type
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setInvestorType(String investorType) {
        this.investorType = investorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.investment_amount
     *
     * @return the value of tyc_events_invest_investors.investment_amount
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Double getInvestmentAmount() {
        return investmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.investment_amount
     *
     * @param investmentAmount the value for tyc_events_invest_investors.investment_amount
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setInvestmentAmount(Double investmentAmount) {
        this.investmentAmount = investmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.invest_mode
     *
     * @return the value of tyc_events_invest_investors.invest_mode
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getInvestMode() {
        return investMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.invest_mode
     *
     * @param investMode the value for tyc_events_invest_investors.invest_mode
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setInvestMode(String investMode) {
        this.investMode = investMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.direct_investor_id
     *
     * @return the value of tyc_events_invest_investors.direct_investor_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getDirectInvestorId() {
        return directInvestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.direct_investor_id
     *
     * @param directInvestorId the value for tyc_events_invest_investors.direct_investor_id
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setDirectInvestorId(String directInvestorId) {
        this.directInvestorId = directInvestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.direct_investor_name
     *
     * @return the value of tyc_events_invest_investors.direct_investor_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getDirectInvestorName() {
        return directInvestorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.direct_investor_name
     *
     * @param directInvestorName the value for tyc_events_invest_investors.direct_investor_name
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setDirectInvestorName(String directInvestorName) {
        this.directInvestorName = directInvestorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.investor_shortname
     *
     * @return the value of tyc_events_invest_investors.investor_shortname
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getInvestorShortname() {
        return investorShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.investor_shortname
     *
     * @param investorShortname the value for tyc_events_invest_investors.investor_shortname
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setInvestorShortname(String investorShortname) {
        this.investorShortname = investorShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.direct_investor_shortname
     *
     * @return the value of tyc_events_invest_investors.direct_investor_shortname
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public String getDirectInvestorShortname() {
        return directInvestorShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.direct_investor_shortname
     *
     * @param directInvestorShortname the value for tyc_events_invest_investors.direct_investor_shortname
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setDirectInvestorShortname(String directInvestorShortname) {
        this.directInvestorShortname = directInvestorShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.status
     *
     * @return the value of tyc_events_invest_investors.status
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.status
     *
     * @param status the value for tyc_events_invest_investors.status
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.created_at
     *
     * @return the value of tyc_events_invest_investors.created_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.created_at
     *
     * @param createdAt the value for tyc_events_invest_investors.created_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tyc_events_invest_investors.updated_at
     *
     * @return the value of tyc_events_invest_investors.updated_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tyc_events_invest_investors.updated_at
     *
     * @param updatedAt the value for tyc_events_invest_investors.updated_at
     *
     * @mbggenerated Sat Sep 30 13:38:40 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}